2025-05-22 22:33:17,883 INFO    StreamThr :30740 [internal.py:wandb_internal():86] W&B internal server running at pid: 30740, started at: 2025-05-22 22:33:17.882574
2025-05-22 22:33:17,883 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status
2025-05-22 22:33:17,885 INFO    WriterThread:30740 [datastore.py:open_for_write():85] open: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\run-2qvbwetj.wandb
2025-05-22 22:33:17,887 DEBUG   SenderThread:30740 [sender.py:send():379] send: header
2025-05-22 22:33:17,887 DEBUG   SenderThread:30740 [sender.py:send():379] send: run
2025-05-22 22:33:19,406 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: check_version
2025-05-22 22:33:19,407 INFO    SenderThread:30740 [dir_watcher.py:__init__():211] watching files in: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files
2025-05-22 22:33:19,407 INFO    SenderThread:30740 [sender.py:_start_run_threads():1121] run started: 2qvbwetj with start time 1747924397.884563
2025-05-22 22:33:19,407 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: check_version
2025-05-22 22:33:20,400 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: run_start
2025-05-22 22:33:20,575 DEBUG   HandlerThread:30740 [system_info.py:__init__():32] System info init
2025-05-22 22:33:20,575 DEBUG   HandlerThread:30740 [system_info.py:__init__():47] System info init done
2025-05-22 22:33:20,575 INFO    HandlerThread:30740 [system_monitor.py:start():181] Starting system monitor
2025-05-22 22:33:20,576 INFO    SystemMonitor:30740 [system_monitor.py:_start():145] Starting system asset monitoring threads
2025-05-22 22:33:20,581 INFO    HandlerThread:30740 [system_monitor.py:probe():201] Collecting system info
2025-05-22 22:33:20,581 INFO    SystemMonitor:30740 [interfaces.py:start():190] Started cpu monitoring
2025-05-22 22:33:20,582 INFO    SystemMonitor:30740 [interfaces.py:start():190] Started disk monitoring
2025-05-22 22:33:20,582 INFO    SystemMonitor:30740 [interfaces.py:start():190] Started gpu monitoring
2025-05-22 22:33:20,583 INFO    SystemMonitor:30740 [interfaces.py:start():190] Started memory monitoring
2025-05-22 22:33:20,590 INFO    SystemMonitor:30740 [interfaces.py:start():190] Started network monitoring
2025-05-22 22:33:20,604 DEBUG   HandlerThread:30740 [system_info.py:probe():196] Probing system
2025-05-22 22:33:20,604 DEBUG   HandlerThread:30740 [gitlib.py:_init_repo():53] git repository is invalid
2025-05-22 22:33:20,604 DEBUG   HandlerThread:30740 [system_info.py:probe():244] Probing system done
2025-05-22 22:33:20,604 DEBUG   HandlerThread:30740 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.19', 'heartbeatAt': '2025-05-22T14:33:20.604203', 'startedAt': '2025-05-22T14:33:17.880046', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'D:\\github\\Opt\\main\\main.py', 'codePathLocal': 'main.py', 'codePath': 'main.py', 'host': 'DESKTOP-RVG428G', 'username': 'HanlinWang', 'executable': 'D:\\anaconda\\envs\\agent3\\python.exe', 'cpu_count': 24, 'cpu_count_logical': 32, 'cpu_freq': {'current': 2200.0, 'min': 0.0, 'max': 2200.0}, 'cpu_freq_per_core': [{'current': 2200.0, 'min': 0.0, 'max': 2200.0}], 'disk': {'/': {'total': 620.9248008728027, 'used': 527.4570617675781}}, 'gpu': 'NVIDIA GeForce RTX 4070 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4070 Laptop GPU', 'memory_total': 8585740288}], 'memory': {'total': 31.74596405029297}}
2025-05-22 22:33:20,604 INFO    HandlerThread:30740 [system_monitor.py:probe():211] Finished collecting system info
2025-05-22 22:33:20,604 INFO    HandlerThread:30740 [system_monitor.py:probe():214] Publishing system info
2025-05-22 22:33:20,604 DEBUG   HandlerThread:30740 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2025-05-22 22:33:20,605 DEBUG   HandlerThread:30740 [system_info.py:_save_pip():68] Saving pip packages done
2025-05-22 22:33:20,605 DEBUG   HandlerThread:30740 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2025-05-22 22:33:21,426 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_created():271] file/dir created: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\requirements.txt
2025-05-22 22:33:21,426 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_created():271] file/dir created: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\conda-environment.yaml
2025-05-22 22:33:38,194 DEBUG   HandlerThread:30740 [system_info.py:_save_conda():87] Saving conda packages done
2025-05-22 22:33:38,194 INFO    HandlerThread:30740 [system_monitor.py:probe():216] Finished publishing system info
2025-05-22 22:33:38,198 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:33:38,198 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:33:38,198 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:33:38,198 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:33:38,198 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:33:38,198 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:33:38,199 DEBUG   SenderThread:30740 [sender.py:send():379] send: files
2025-05-22 22:33:38,199 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2025-05-22 22:33:38,204 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: stop_status
2025-05-22 22:33:38,204 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: stop_status
2025-05-22 22:33:38,205 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: internal_messages
2025-05-22 22:33:38,563 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\conda-environment.yaml
2025-05-22 22:33:38,563 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_created():271] file/dir created: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\wandb-metadata.json
2025-05-22 22:33:38,572 DEBUG   SenderThread:30740 [sender.py:send():379] send: telemetry
2025-05-22 22:33:38,572 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:33:39,566 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_created():271] file/dir created: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\output.log
2025-05-22 22:33:39,674 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: partial_history
2025-05-22 22:33:39,675 DEBUG   SenderThread:30740 [sender.py:send():379] send: history
2025-05-22 22:33:39,675 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: summary_record
2025-05-22 22:33:39,676 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:39,953 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: partial_history
2025-05-22 22:33:39,954 DEBUG   SenderThread:30740 [sender.py:send():379] send: history
2025-05-22 22:33:39,954 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: summary_record
2025-05-22 22:33:39,954 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:40,079 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: partial_history
2025-05-22 22:33:40,080 DEBUG   SenderThread:30740 [sender.py:send():379] send: history
2025-05-22 22:33:40,080 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: summary_record
2025-05-22 22:33:40,080 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:40,568 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_created():271] file/dir created: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\wandb-summary.json
2025-05-22 22:33:40,585 WARNING FileStreamThread:30740 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/file_stream (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)'))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x00000191F5C81FD0>>, timeout=180), args: ('https://api.wandb.ai/files/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/file_stream',), kwargs: {'json': {'files': {'wandb-history.jsonl': {'offset': 0, 'content': ['{"Iter_1/AvgTrainLoss_epoch": 18.318776448567707, "Iter_1/TestLoss_epoch": 9.518993377685547, "global_epoch": 4, "iteration": 1, "epoch_in_iteration": 5, "_timestamp": 1747924419.6745849, "_runtime": 21.790021896362305, "_step": 0}']}}, 'dropped': 0}}
2025-05-22 22:33:40,645 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:33:40,645 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1191'}
2025-05-22 22:33:40,645 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:33:40,776 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: partial_history
2025-05-22 22:33:40,776 DEBUG   SenderThread:30740 [sender.py:send():379] send: history
2025-05-22 22:33:40,776 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: summary_record
2025-05-22 22:33:40,776 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:41,054 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: partial_history
2025-05-22 22:33:41,054 DEBUG   SenderThread:30740 [sender.py:send():379] send: history
2025-05-22 22:33:41,055 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: summary_record
2025-05-22 22:33:41,055 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:41,163 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: partial_history
2025-05-22 22:33:41,163 DEBUG   SenderThread:30740 [sender.py:send():379] send: history
2025-05-22 22:33:41,163 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: summary_record
2025-05-22 22:33:41,164 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:41,582 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\wandb-summary.json
2025-05-22 22:33:41,582 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\output.log
2025-05-22 22:33:41,778 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: partial_history
2025-05-22 22:33:41,778 DEBUG   SenderThread:30740 [sender.py:send():379] send: history
2025-05-22 22:33:41,778 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: summary_record
2025-05-22 22:33:41,779 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:42,050 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: partial_history
2025-05-22 22:33:42,050 DEBUG   SenderThread:30740 [sender.py:send():379] send: history
2025-05-22 22:33:42,050 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: summary_record
2025-05-22 22:33:42,051 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:42,181 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: partial_history
2025-05-22 22:33:42,182 DEBUG   SenderThread:30740 [sender.py:send():379] send: history
2025-05-22 22:33:42,182 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: summary_record
2025-05-22 22:33:42,182 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:42,494 DEBUG   SenderThread:30740 [sender.py:send():379] send: telemetry
2025-05-22 22:33:42,495 DEBUG   SenderThread:30740 [sender.py:send():379] send: exit
2025-05-22 22:33:42,495 INFO    SenderThread:30740 [sender.py:send_exit():584] handling exit code: 0
2025-05-22 22:33:42,495 INFO    SenderThread:30740 [sender.py:send_exit():586] handling runtime: 22
2025-05-22 22:33:42,495 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:42,495 INFO    SenderThread:30740 [sender.py:send_exit():592] send defer
2025-05-22 22:33:42,495 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:42,497 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 0
2025-05-22 22:33:42,497 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:42,497 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 0
2025-05-22 22:33:42,497 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 1
2025-05-22 22:33:42,497 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:42,497 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 1
2025-05-22 22:33:42,497 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:42,497 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 1
2025-05-22 22:33:42,497 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 2
2025-05-22 22:33:42,497 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:42,497 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 2
2025-05-22 22:33:42,497 INFO    HandlerThread:30740 [system_monitor.py:finish():190] Stopping system monitor
2025-05-22 22:33:42,497 DEBUG   SystemMonitor:30740 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2025-05-22 22:33:42,497 DEBUG   SystemMonitor:30740 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2025-05-22 22:33:42,497 DEBUG   SystemMonitor:30740 [system_monitor.py:_start():170] Publishing last batch of metrics
2025-05-22 22:33:42,503 INFO    HandlerThread:30740 [interfaces.py:finish():202] Joined cpu monitor
2025-05-22 22:33:42,503 INFO    HandlerThread:30740 [interfaces.py:finish():202] Joined disk monitor
2025-05-22 22:33:42,536 INFO    HandlerThread:30740 [interfaces.py:finish():202] Joined gpu monitor
2025-05-22 22:33:42,536 INFO    HandlerThread:30740 [interfaces.py:finish():202] Joined memory monitor
2025-05-22 22:33:42,536 INFO    HandlerThread:30740 [interfaces.py:finish():202] Joined network monitor
2025-05-22 22:33:42,536 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:42,536 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 2
2025-05-22 22:33:42,536 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 3
2025-05-22 22:33:42,536 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:42,536 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 3
2025-05-22 22:33:42,536 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:42,536 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 3
2025-05-22 22:33:42,536 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 4
2025-05-22 22:33:42,536 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:42,536 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 4
2025-05-22 22:33:42,536 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:42,536 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 4
2025-05-22 22:33:42,536 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 5
2025-05-22 22:33:42,537 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:42,537 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 5
2025-05-22 22:33:42,537 DEBUG   SenderThread:30740 [sender.py:send():379] send: summary
2025-05-22 22:33:42,537 INFO    SenderThread:30740 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2025-05-22 22:33:42,537 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:42,537 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 5
2025-05-22 22:33:42,537 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 6
2025-05-22 22:33:42,537 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:42,537 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 6
2025-05-22 22:33:42,538 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:42,538 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 6
2025-05-22 22:33:42,540 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:33:42,594 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\wandb-summary.json
2025-05-22 22:33:42,594 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\output.log
2025-05-22 22:33:42,805 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:33:42,805 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1191'}
2025-05-22 22:33:42,805 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:33:42,883 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 7
2025-05-22 22:33:42,883 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:42,884 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 7
2025-05-22 22:33:42,884 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:42,884 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 7
2025-05-22 22:33:43,507 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: poll_exit
2025-05-22 22:33:43,602 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\config.yaml
2025-05-22 22:33:44,064 WARNING FileStreamThread:30740 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/file_stream (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)'))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x00000191F5C81FD0>>, timeout=180), args: ('https://api.wandb.ai/files/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/file_stream',), kwargs: {'json': {'files': {'wandb-history.jsonl': {'offset': 0, 'content': ['{"Iter_1/AvgTrainLoss_epoch": 18.318776448567707, "Iter_1/TestLoss_epoch": 9.518993377685547, "global_epoch": 4, "iteration": 1, "epoch_in_iteration": 5, "_timestamp": 1747924419.6745849, "_runtime": 21.790021896362305, "_step": 0}']}}, 'dropped': 0}}
2025-05-22 22:33:44,608 INFO    Thread-16 :30740 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\output.log
2025-05-22 22:33:46,004 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:33:46,004 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1191'}
2025-05-22 22:33:46,004 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:33:46,004 INFO    wandb-upload_0:30740 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\anaconda\envs\agent3\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\anaconda\envs\agent3\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "D:\anaconda\envs\agent3\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1133)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2541, in upload_file
    response = self._upload_file_session.put(
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2572, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2541, in upload_file
    response = self._upload_file_session.put(
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-05-22 22:33:46,034 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 8
2025-05-22 22:33:46,072 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: poll_exit
2025-05-22 22:33:46,072 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:46,072 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 8
2025-05-22 22:33:46,072 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:46,073 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 8
2025-05-22 22:33:46,073 INFO    SenderThread:30740 [job_builder.py:build():281] Attempting to build job artifact
2025-05-22 22:33:46,073 INFO    SenderThread:30740 [job_builder.py:_get_source_type():404] no source found
2025-05-22 22:33:46,073 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 9
2025-05-22 22:33:46,073 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:46,073 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 9
2025-05-22 22:33:46,073 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:46,074 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 9
2025-05-22 22:33:46,074 INFO    SenderThread:30740 [dir_watcher.py:finish():358] shutting down directory watcher
2025-05-22 22:33:46,632 INFO    SenderThread:30740 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\output.log
2025-05-22 22:33:46,632 INFO    SenderThread:30740 [dir_watcher.py:finish():388] scan: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files
2025-05-22 22:33:46,632 INFO    SenderThread:30740 [dir_watcher.py:finish():402] scan save: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\conda-environment.yaml conda-environment.yaml
2025-05-22 22:33:46,632 INFO    SenderThread:30740 [dir_watcher.py:finish():402] scan save: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\config.yaml config.yaml
2025-05-22 22:33:46,633 INFO    SenderThread:30740 [dir_watcher.py:finish():402] scan save: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\output.log output.log
2025-05-22 22:33:46,633 INFO    SenderThread:30740 [dir_watcher.py:finish():402] scan save: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\requirements.txt requirements.txt
2025-05-22 22:33:46,633 INFO    SenderThread:30740 [dir_watcher.py:finish():402] scan save: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\wandb-metadata.json wandb-metadata.json
2025-05-22 22:33:46,633 INFO    SenderThread:30740 [dir_watcher.py:finish():402] scan save: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\wandb-summary.json wandb-summary.json
2025-05-22 22:33:46,633 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 10
2025-05-22 22:33:46,633 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:33:46,634 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 10
2025-05-22 22:33:46,634 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:33:46,634 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 10
2025-05-22 22:33:46,634 INFO    SenderThread:30740 [file_pusher.py:finish():175] shutting down file pusher
2025-05-22 22:33:47,825 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:33:47,826 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9629'}
2025-05-22 22:33:47,826 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:33:48,538 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:33:49,161 INFO    wandb-upload_2:30740 [upload_job.py:push():131] Uploaded file D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\config.yaml
2025-05-22 22:33:49,945 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:33:49,946 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9629'}
2025-05-22 22:33:49,946 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:33:49,993 WARNING FileStreamThread:30740 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/file_stream (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)'))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x00000191F5C81FD0>>, timeout=180), args: ('https://api.wandb.ai/files/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/file_stream',), kwargs: {'json': {'files': {'wandb-history.jsonl': {'offset': 0, 'content': ['{"Iter_1/AvgTrainLoss_epoch": 18.318776448567707, "Iter_1/TestLoss_epoch": 9.518993377685547, "global_epoch": 4, "iteration": 1, "epoch_in_iteration": 5, "_timestamp": 1747924419.6745849, "_runtime": 21.790021896362305, "_step": 0}']}}, 'dropped': 0}}
2025-05-22 22:33:51,413 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:33:51,413 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1191'}
2025-05-22 22:33:51,413 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:33:51,413 INFO    wandb-upload_0:30740 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\anaconda\envs\agent3\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\anaconda\envs\agent3\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "D:\anaconda\envs\agent3\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1133)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2541, in upload_file
    response = self._upload_file_session.put(
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2572, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2541, in upload_file
    response = self._upload_file_session.put(
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-05-22 22:33:51,687 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:33:52,962 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:33:52,962 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9629'}
2025-05-22 22:33:52,962 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:33:53,585 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:33:56,745 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:33:58,110 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:33:58,110 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9629'}
2025-05-22 22:33:58,110 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:33:58,612 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:33:59,612 WARNING FileStreamThread:30740 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/file_stream (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)'))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x00000191F5C81FD0>>, timeout=180), args: ('https://api.wandb.ai/files/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/file_stream',), kwargs: {'json': {'files': {'wandb-history.jsonl': {'offset': 0, 'content': ['{"Iter_1/AvgTrainLoss_epoch": 18.318776448567707, "Iter_1/TestLoss_epoch": 9.518993377685547, "global_epoch": 4, "iteration": 1, "epoch_in_iteration": 5, "_timestamp": 1747924419.6745849, "_runtime": 21.790021896362305, "_step": 0}']}}, 'dropped': 0}}
2025-05-22 22:34:01,487 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:34:01,487 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1191'}
2025-05-22 22:34:01,487 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:34:01,782 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:03,644 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:06,827 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:08,287 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/conda-environment.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143346Z&X-Goog-Expires=86399&X-Goog-Signature=93d6a5270a180db88ddb9da80dfc2953399c6bd22c10379e80702a4a8547af11770296e6b7ed97774cec88651cddf60c6e20ca88bf2c2384baf97c3acff9d4fc4ea11e67b109d081d0612a4035880f72fbd9accdf924aa5d0d832f7a8ff8fa780e1a32bbd34a8d6f2fa923023555207e89f1e07635da70efcb8136b835580f5bc2e286a90a18887eedc04bb51fd21773b2cb9021ccb0e08d87399b8d57787dd17c8ced2a9101feb9a2e1a959d667a2abee8747f29db616a8ccad6c03123ba06ac2e4f392adc90f9ad8de0ddaf1b13cdd42e59b8e301a46a216e0448b671b02817883246fd1f0d92da9c490901bb1ccb7b6448ed99be9120ea344b2c869b1fc9d&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:34:08,287 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9629'}
2025-05-22 22:34:08,287 ERROR   wandb-upload_1:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:34:08,680 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:10,540 ERROR   wandb-upload_5:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143409Z&X-Goog-Expires=86399&X-Goog-Signature=867f364c7590ea3c8ae397908d859e77d3d63c4b46b75fb9b2e806102bf78a63a7070c4bb97cc7f0f5ca4857e5e95054751581c27ae84833485947f0e92d3e30a9c43b0e514065392d38a4e69630f0d5835ecf08ccc7d1e81abbd5eed8fc3b03e02caf89757d14d18fa29f461415fb9dfe49c23d72c8913d9c4d29b29ed60ba802b0f30cdb77db8539da09b7b236fa2b9f8b4346916231622ad547fd1a93b1bb713285433586e975da5c4482b6e96e8fa3a175404b42439a347b561af4e3d2054840ea0c144918ffd579df6a1e9a63ee57f6e112bb0ea60592b8b46cd91d8cfc898f6409e826d938ac90088404e9b3ec5cc9b242ce451edc118c127a066849e3&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143409Z&X-Goog-Expires=86399&X-Goog-Signature=867f364c7590ea3c8ae397908d859e77d3d63c4b46b75fb9b2e806102bf78a63a7070c4bb97cc7f0f5ca4857e5e95054751581c27ae84833485947f0e92d3e30a9c43b0e514065392d38a4e69630f0d5835ecf08ccc7d1e81abbd5eed8fc3b03e02caf89757d14d18fa29f461415fb9dfe49c23d72c8913d9c4d29b29ed60ba802b0f30cdb77db8539da09b7b236fa2b9f8b4346916231622ad547fd1a93b1bb713285433586e975da5c4482b6e96e8fa3a175404b42439a347b561af4e3d2054840ea0c144918ffd579df6a1e9a63ee57f6e112bb0ea60592b8b46cd91d8cfc898f6409e826d938ac90088404e9b3ec5cc9b242ce451edc118c127a066849e3&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:34:10,540 ERROR   wandb-upload_5:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '756'}
2025-05-22 22:34:10,540 ERROR   wandb-upload_5:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:34:11,867 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:12,761 ERROR   wandb-upload_5:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143409Z&X-Goog-Expires=86399&X-Goog-Signature=867f364c7590ea3c8ae397908d859e77d3d63c4b46b75fb9b2e806102bf78a63a7070c4bb97cc7f0f5ca4857e5e95054751581c27ae84833485947f0e92d3e30a9c43b0e514065392d38a4e69630f0d5835ecf08ccc7d1e81abbd5eed8fc3b03e02caf89757d14d18fa29f461415fb9dfe49c23d72c8913d9c4d29b29ed60ba802b0f30cdb77db8539da09b7b236fa2b9f8b4346916231622ad547fd1a93b1bb713285433586e975da5c4482b6e96e8fa3a175404b42439a347b561af4e3d2054840ea0c144918ffd579df6a1e9a63ee57f6e112bb0ea60592b8b46cd91d8cfc898f6409e826d938ac90088404e9b3ec5cc9b242ce451edc118c127a066849e3&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143409Z&X-Goog-Expires=86399&X-Goog-Signature=867f364c7590ea3c8ae397908d859e77d3d63c4b46b75fb9b2e806102bf78a63a7070c4bb97cc7f0f5ca4857e5e95054751581c27ae84833485947f0e92d3e30a9c43b0e514065392d38a4e69630f0d5835ecf08ccc7d1e81abbd5eed8fc3b03e02caf89757d14d18fa29f461415fb9dfe49c23d72c8913d9c4d29b29ed60ba802b0f30cdb77db8539da09b7b236fa2b9f8b4346916231622ad547fd1a93b1bb713285433586e975da5c4482b6e96e8fa3a175404b42439a347b561af4e3d2054840ea0c144918ffd579df6a1e9a63ee57f6e112bb0ea60592b8b46cd91d8cfc898f6409e826d938ac90088404e9b3ec5cc9b242ce451edc118c127a066849e3&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:34:12,761 ERROR   wandb-upload_5:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '756'}
2025-05-22 22:34:12,761 ERROR   wandb-upload_5:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:34:13,704 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:16,192 ERROR   wandb-upload_5:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143409Z&X-Goog-Expires=86399&X-Goog-Signature=867f364c7590ea3c8ae397908d859e77d3d63c4b46b75fb9b2e806102bf78a63a7070c4bb97cc7f0f5ca4857e5e95054751581c27ae84833485947f0e92d3e30a9c43b0e514065392d38a4e69630f0d5835ecf08ccc7d1e81abbd5eed8fc3b03e02caf89757d14d18fa29f461415fb9dfe49c23d72c8913d9c4d29b29ed60ba802b0f30cdb77db8539da09b7b236fa2b9f8b4346916231622ad547fd1a93b1bb713285433586e975da5c4482b6e96e8fa3a175404b42439a347b561af4e3d2054840ea0c144918ffd579df6a1e9a63ee57f6e112bb0ea60592b8b46cd91d8cfc898f6409e826d938ac90088404e9b3ec5cc9b242ce451edc118c127a066849e3&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143409Z&X-Goog-Expires=86399&X-Goog-Signature=867f364c7590ea3c8ae397908d859e77d3d63c4b46b75fb9b2e806102bf78a63a7070c4bb97cc7f0f5ca4857e5e95054751581c27ae84833485947f0e92d3e30a9c43b0e514065392d38a4e69630f0d5835ecf08ccc7d1e81abbd5eed8fc3b03e02caf89757d14d18fa29f461415fb9dfe49c23d72c8913d9c4d29b29ed60ba802b0f30cdb77db8539da09b7b236fa2b9f8b4346916231622ad547fd1a93b1bb713285433586e975da5c4482b6e96e8fa3a175404b42439a347b561af4e3d2054840ea0c144918ffd579df6a1e9a63ee57f6e112bb0ea60592b8b46cd91d8cfc898f6409e826d938ac90088404e9b3ec5cc9b242ce451edc118c127a066849e3&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:34:16,192 ERROR   wandb-upload_5:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '756'}
2025-05-22 22:34:16,192 ERROR   wandb-upload_5:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:34:16,192 INFO    wandb-upload_5:30740 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\anaconda\envs\agent3\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\anaconda\envs\agent3\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "D:\anaconda\envs\agent3\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1133)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "D:\anaconda\envs\agent3\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143409Z&X-Goog-Expires=86399&X-Goog-Signature=867f364c7590ea3c8ae397908d859e77d3d63c4b46b75fb9b2e806102bf78a63a7070c4bb97cc7f0f5ca4857e5e95054751581c27ae84833485947f0e92d3e30a9c43b0e514065392d38a4e69630f0d5835ecf08ccc7d1e81abbd5eed8fc3b03e02caf89757d14d18fa29f461415fb9dfe49c23d72c8913d9c4d29b29ed60ba802b0f30cdb77db8539da09b7b236fa2b9f8b4346916231622ad547fd1a93b1bb713285433586e975da5c4482b6e96e8fa3a175404b42439a347b561af4e3d2054840ea0c144918ffd579df6a1e9a63ee57f6e112bb0ea60592b8b46cd91d8cfc898f6409e826d938ac90088404e9b3ec5cc9b242ce451edc118c127a066849e3&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2541, in upload_file
    response = self._upload_file_session.put(
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143409Z&X-Goog-Expires=86399&X-Goog-Signature=867f364c7590ea3c8ae397908d859e77d3d63c4b46b75fb9b2e806102bf78a63a7070c4bb97cc7f0f5ca4857e5e95054751581c27ae84833485947f0e92d3e30a9c43b0e514065392d38a4e69630f0d5835ecf08ccc7d1e81abbd5eed8fc3b03e02caf89757d14d18fa29f461415fb9dfe49c23d72c8913d9c4d29b29ed60ba802b0f30cdb77db8539da09b7b236fa2b9f8b4346916231622ad547fd1a93b1bb713285433586e975da5c4482b6e96e8fa3a175404b42439a347b561af4e3d2054840ea0c144918ffd579df6a1e9a63ee57f6e112bb0ea60592b8b46cd91d8cfc898f6409e826d938ac90088404e9b3ec5cc9b242ce451edc118c127a066849e3&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2572, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "D:\anaconda\envs\agent3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2541, in upload_file
    response = self._upload_file_session.put(
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\envs\agent3\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-05-22 22:34:16,914 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:18,742 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:20,840 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2548] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/939531372-south-china-university-of-technology/tracin_active_learning/2qvbwetj/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250522%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250522T143339Z&X-Goog-Expires=86399&X-Goog-Signature=a176f0baaec7a3122ecdda1ebdf4c1d60f1843cb795bca528227e5525237134988151e4265b449583e019afaffabf7a2909b83ebbc55454d7a25edb4b15870bf95607c2d3440f3824f782fc4a6662c35cbf59824c677c658fdd884571126eaeee80b4cdcce228de980d0c9f8ef4cc500ade711232edb0d1d73474fe2c723e0053b24dbae0e4165c06610d33482cfd482fd7bb391c1a8b1f3b2b69ac3fb7b1d2c79573d09d73a7119c037acd6f929900031c7d816fc24b92da92e669e43543c56daf0a4ef44c253a8caab8d4ab6b9cd7b869f0a66dad3ed12b7bcde0ca1e5a23ad67669cecffa92bfcff769ed774379a1759777563f19089c78f6a965873dfd5f&X-Goog-SignedHeaders=host&X-User=939531372 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))
2025-05-22 22:34:20,840 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2550] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1191'}
2025-05-22 22:34:20,840 ERROR   wandb-upload_0:30740 [internal_api.py:upload_file():2552] upload_file response body: 
2025-05-22 22:34:21,091 INFO    wandb-upload_5:30740 [upload_job.py:push():131] Uploaded file D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\wandb-summary.json
2025-05-22 22:34:21,949 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:23,780 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:25,728 INFO    wandb-upload_1:30740 [upload_job.py:push():131] Uploaded file D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\conda-environment.yaml
2025-05-22 22:34:26,976 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:28,450 INFO    wandb-upload_4:30740 [upload_job.py:push():131] Uploaded file D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\requirements.txt
2025-05-22 22:34:28,818 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:32,016 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:32,251 INFO    wandb-upload_3:30740 [upload_job.py:push():131] Uploaded file D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\files\output.log
2025-05-22 22:34:33,864 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:37,050 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:38,885 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:42,085 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:43,921 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:47,142 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:48,974 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:52,179 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:54,022 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:57,219 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: status_report
2025-05-22 22:34:59,072 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: keepalive
2025-05-22 22:34:59,247 INFO    wandb-upload_0:30740 [upload_job.py:push():131] Uploaded file C:\Users\HANLIN~1\AppData\Local\Temp\tmp77yakgx4wandb\55a2m6in-wandb-metadata.json
2025-05-22 22:34:59,457 INFO    Thread-15 :30740 [sender.py:transition_state():612] send defer: 11
2025-05-22 22:34:59,457 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:34:59,457 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 11
2025-05-22 22:34:59,457 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:34:59,457 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 11
2025-05-22 22:34:59,457 INFO    SenderThread:30740 [file_pusher.py:join():181] waiting for file pusher
2025-05-22 22:34:59,457 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 12
2025-05-22 22:34:59,457 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:34:59,458 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 12
2025-05-22 22:34:59,458 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:34:59,458 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 12
2025-05-22 22:34:59,458 INFO    SenderThread:30740 [file_stream.py:finish():594] file stream finish called
2025-05-22 22:34:59,781 INFO    SenderThread:30740 [file_stream.py:finish():598] file stream finish is done
2025-05-22 22:34:59,781 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 13
2025-05-22 22:34:59,781 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:34:59,781 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 13
2025-05-22 22:34:59,781 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:34:59,781 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 13
2025-05-22 22:34:59,781 INFO    SenderThread:30740 [sender.py:transition_state():612] send defer: 14
2025-05-22 22:34:59,781 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: defer
2025-05-22 22:34:59,781 INFO    HandlerThread:30740 [handler.py:handle_request_defer():170] handle defer: 14
2025-05-22 22:34:59,782 DEBUG   SenderThread:30740 [sender.py:send():379] send: final
2025-05-22 22:34:59,782 DEBUG   SenderThread:30740 [sender.py:send():379] send: footer
2025-05-22 22:34:59,782 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: defer
2025-05-22 22:34:59,782 INFO    SenderThread:30740 [sender.py:send_request_defer():608] handle sender defer: 14
2025-05-22 22:34:59,782 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: internal_messages
2025-05-22 22:34:59,783 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: poll_exit
2025-05-22 22:34:59,783 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: server_info
2025-05-22 22:34:59,783 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: get_summary
2025-05-22 22:34:59,783 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: sampled_history
2025-05-22 22:34:59,783 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: poll_exit
2025-05-22 22:34:59,784 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: job_info
2025-05-22 22:34:59,784 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: server_info
2025-05-22 22:35:00,093 DEBUG   SenderThread:30740 [sender.py:send_request():406] send_request: job_info
2025-05-22 22:35:00,094 DEBUG   HandlerThread:30740 [handler.py:handle_request():144] handle_request: shutdown
2025-05-22 22:35:00,094 INFO    HandlerThread:30740 [handler.py:finish():840] shutting down handler
2025-05-22 22:35:00,797 INFO    WriterThread:30740 [datastore.py:close():294] close: D:\github\Opt\main\wandb\run-20250522_223317-2qvbwetj\run-2qvbwetj.wandb
2025-05-22 22:35:01,108 INFO    SenderThread:30740 [sender.py:finish():1531] shutting down sender
2025-05-22 22:35:01,108 INFO    SenderThread:30740 [file_pusher.py:finish():175] shutting down file pusher
2025-05-22 22:35:01,108 INFO    SenderThread:30740 [file_pusher.py:join():181] waiting for file pusher
